language: node_js
node_js:
  - '9'
cache:
  directories:
    - 'node_modules'
install:
  - npm install
script:
  - npm run build
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
